# Copyright 2025-2026 Braden Ganetsky
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: 'Setup MSVC'
description: 'Downloads, installs, and sets up the environment for a particular version of MSVC'
author: 'Braden Ganetsky'

inputs:
  vs-version:
    required: true
  install-path:
    default: ..\vs-install

runs:
  using: "composite"
  steps:
    - name: Download and install VS Build Tools, and setup MSVC environment
      shell: powershell
      env:
        INPUT_VERSION: "${{ inputs.vs-version }}"
        INSTALL_PATH: "${{ inputs.install-path }}"
      run: |
        ${{ github.action_path }}/install_msvc.ps1 -inputVersion $env:INPUT_VERSION -installPath $env:INSTALL_PATH

        cmd /c "$env:INSTALL_PATH\VC\Auxiliary\Build\vcvars64.bat >nul && set" |
          ForEach-Object {
            Add-Content $env:GITHUB_ENV $_
          }
